version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OWNER_TAG
      - BOT_TOKEN
      - API_ID
      - API_HASH
    volumes:
      - .:/app